version: "3.8"

services:
  django: &django
    build:
      context: .
    ports:
      - "8200:8200"

    command: ["sh", "./compose/start.sh"]
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=liquid
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=debug
      - POSTGRES_PASSWORD=debug
      - DATABASE_URL=postgres://kwasa:1234@localhost:5432/amiribd

volumes:
  postgres_data:
