
# version: "3.8"
services:

  redis:
    image: redis:alpine
    container_name: redis

  db:
    image: postgres
    volumes:
     - postgres_data:/var/lib/postgresql/data
    environment:
     - POSTGRES_DB=liquid
     - POSTGRES_HOST=localhost
     - POSTGRES_USER=debug
     - POSTGRES_PASSWORD=debug
    container_name: postgres_db

  app:
   build:
     context: .
   ports:
    - "8000:8000"
   volumes:
    - .:/app
   command: python manage.py runserver 0.0.0.0:8000
   depends_on:
    - db

  # celery worker
  celery:
    restart: always
    build:
      context: .
    command: celery -A core worker -l DEBUG
    container_name: celery
    depends_on:
      - db
      - redis
      - app



volumes:
  postgres_data: