version: "3.8"

services:
  django: &django
    build:
      context: .
    ports:
      - "8200:8200"

    command: ["sh", "./compose/start.sh"]
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=liquid
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=debug
      - POSTGRES_PASSWORD=debug
      - DATABASE_URL=postgres://postgres:1234@localhost:5432/amiribd
      # - DATABASE_URL=postgresql://amiribd_owner:vIlVOSJ0hs3C@ep-empty-sun-a5o1i2jp-pooler.us-east-2.aws.neon.tech/amiribd?sslmode=require
volumes:
  postgres_data:
