
services:

  redis:
    image: redis:alpine
    container_name: redis

  db_earnkaft:
    image: postgres
    volumes:
     - postgres_data:/var/lib/postgresql/data
    environment:
     - POSTGRES_DB=amiribd
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=1234
    container_name: db_earnkaft_container
    ports:
      - "5433:5432"

  app1:
   build:
     context: .
   ports:
    - "8000:8000"
   volumes:
    - ./app1:/app
   depends_on:
    - db_earnkaft
   restart: always
   env_file:
    - /.env

  app2:
   build:
     context: .
   ports:
    - "8090:8090"
   volumes:
    - ./app2:/app
   depends_on:
    - db_earnkaft
   restart: always
   env_file:
    - /.env

  app3:
   build:
     context: .
   ports:
    - "8091:8091"
   volumes:
    - ./app3:/app
  
   depends_on:
    - db_earnkaft
   restart: always
   env_file:
    - /.env

  # celery worker
  celery:
    restart: always
    build:
      context: .
    command: celery -A core worker -l DEBUG
    container_name: celery
    depends_on:
      - db_earnkaft
      - redis
      - app1
      - app2
      - app3
  api:
    build: 
      context: ./src
    container_name: earnkraft_api_service
    ports:
      - "8001:8001"
    environment:
      - API_VERSION=1.0
      - JWT_AUTH_SECRET=5f001c1f5ef2a6bf0c933c5ae9b887c4fb68c86c2997ad8076e59235
      - REDIS_HOST=0.0.0.0
      - REDIS_PORT=6379
    volumes:
      - ./src:/api
    depends_on:
      - app1
    
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8078:80"
    container_name: earnkraft_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf


volumes:
  postgres_data: