# Generated by Django 5.0.6 on 2024-08-29 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_agent",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="plantform",
            field=models.ManyToManyField(
                blank=True, related_name="plantforms", to="profiles.plantform"
            ),
        ),
        migrations.AddField(
            model_name="plantform",
            name="plantform_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.plantformtype",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="position",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_position",
                to="profiles.position",
            ),
        ),
    ]
