# Generated by Django 5.0.4 on 2024-05-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_position_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantform",
            name="agent",
        ),
        migrations.AddField(
            model_name="agent",
            name="plantform",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="agent_plantform",
                to="profiles.plantform",
            ),
        ),
    ]
