# Generated by Django 5.0.6 on 2024-10-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_subscribed",
            field=models.BooleanField(default=False),
        ),
    ]
