# Generated by Django 5.0.6 on 2024-10-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_validatedemailaddress"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="validatedemailaddress",
            options={
                "managed": False,
                "verbose_name": "Validated Email Address",
                "verbose_name_plural": "Validated Email Address",
            },
        ),
    ]
