# Generated by Django 5.0.4 on 2024-05-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "pending"),
                    ("COMPLETED", "completed"),
                    ("BLOCKED", "blocked"),
                    ("SUSPENDED", "suspended"),
                    ("REPORTED", "reported"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
    ]
