# Generated by Django 5.0.6 on 2024-10-27 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_profile_has_plan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="has_plan",
            new_name="is_waiting_plan_verification",
        ),
    ]
