# Generated by Django 5.1.4 on 2024-12-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_has_plan_profile_is_waiting_plan_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_level',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('VIP', 'VIP')], default='BASIC', max_length=20),
        ),
    ]
