# Generated by Django 5.0.4 on 2024-05-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('COMPLETED', 'completed'), ('BLOCKED', 'blocked'), ('SUSPENDED', 'suspended')], default='PENDING', max_length=255),
        ),
    ]
