# Generated by Django 5.0.4 on 2024-05-05 16:32

import amiribd.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_profile_first_name_profile_last_name_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.GeneratedField(
                db_persist=True,
                expression=amiribd.users.models.ConcatFiels(
                    "first_name", models.Value(" "), "last_name"
                ),
                output_field=models.TextField(),
            ),
        ),
    ]
