# Generated by Django 5.0.4 on 2024-05-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_profile_date_of_birth_profile_phone_number_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.CharField(blank=True, null=True),
        ),
    ]
