# Generated by Django 5.0.4 on 2024-05-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_address_is_address_set"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="is_address_set",
        ),
        migrations.AddField(
            model_name="profile",
            name="is_address_set",
            field=models.BooleanField(default=False),
        ),
    ]
