# Generated by Django 5.0.4 on 2024-05-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_remove_address_is_address_set_profile_is_address_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="kyc_validated",
            field=models.BooleanField(default=False),
        ),
    ]
