# Generated by Django 5.0.4 on 2024-05-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_profile_kyc_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_document_set',
            field=models.BooleanField(default=False),
        ),
    ]
