# Generated by Django 5.0.4 on 2024-05-19 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_profile_plans"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="plans",
        ),
    ]
