# Generated by Django 5.0.6 on 2024-06-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_alter_jobapplication_applicant"),
        ("users", "0026_remove_profile_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="job_applications",
            field=models.ManyToManyField(
                blank=True, related_name="profile_job_applications", to="jobs.job"
            ),
        ),
    ]
