# Generated by Django 5.0.6 on 2024-06-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0035_account_account_ssid"),
        ("users", "0027_profile_job_applications"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="plans",
            field=models.ManyToManyField(blank=True, to="invest.plan"),
        ),
    ]
