# Generated by Django 5.0.6 on 2024-06-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0035_account_account_ssid"),
        ("users", "0028_profile_plans"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="plans",
            field=models.ManyToManyField(
                blank=True, related_name="profile_plans", to="invest.plan"
            ),
        ),
    ]
