# Generated by Django 5.0.6 on 2024-06-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adverts", "0001_initial"),
        ("invest", "0035_account_account_ssid"),
        ("users", "0029_alter_profile_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="adverts",
            field=models.ManyToManyField(blank=True, to="adverts.advert"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="plans",
            field=models.ManyToManyField(blank=True, to="invest.plan"),
        ),
    ]
