# Generated by Django 5.0.6 on 2024-06-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_profile_adverts_alter_profile_plans"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics"),
        ),
    ]
