# Generated by Django 5.0.6 on 2024-07-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_job_bidding_offer_required_and_more"),
        ("users", "0031_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="accepted_job_applications",
            field=models.ManyToManyField(
                blank=True,
                related_name="profile_accepted_job_applications",
                to="jobs.jobapplication",
            ),
        ),
    ]
