# Generated by Django 5.0.6 on 2024-06-04 08:05

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0026_remove_profile_plans"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "regular_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "sales_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("description", models.TextField()),
                ("item_ssid", models.CharField(blank=True, max_length=100, null=True)),
                ("is_sold", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sold_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "discount",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("regular_price"), "-", models.F("sales_price")
                        ),
                        output_field=models.DecimalField(
                            decimal_places=2, default=0.0, max_digits=12
                        ),
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_sale_items",
                        to="users.profile",
                    ),
                ),
                (
                    "sold_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.profile",
                    ),
                ),
            ],
        ),
    ]
