# Generated by Django 5.0.6 on 2024-08-29 07:23

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShopItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "regular_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "sales_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("description", models.TextField()),
                ("item_ssid", models.CharField(blank=True, max_length=100, null=True)),
                ("is_sold", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sold_at", models.DateTimeField(blank=True, null=True)),
                (
                    "discount",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("regular_price"), "-", models.F("sales_price")
                        ),
                        output_field=models.DecimalField(
                            decimal_places=2, default=0.0, max_digits=12
                        ),
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShopItemOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "price_offer",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "email_or_phone",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
