# Generated by Django 5.0.6 on 2024-06-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0001_initial"),
        ("users", "0026_remove_profile_plans"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Item",
            new_name="ShopItem",
        ),
    ]
