# Generated by Django 5.0.6 on 2024-08-29 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shops", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopitem",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_sale_items",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="shopitem",
            name="sold_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="shopitemoffer",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_item_offer_client",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="shopitemoffer",
            name="shop_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_item_offer",
                to="shops.shopitem",
            ),
        ),
    ]
