# Generated by Django 5.0.6 on 2024-06-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0002_rename_item_shopitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopitem",
            name="sold_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
