# Generated by Django 5.0.6 on 2024-06-04 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0003_alter_shopitem_sold_at"),
        ("users", "0026_remove_profile_plans"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopItemOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "price_offer",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "email_or_phone",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_item_offer_client",
                        to="users.profile",
                    ),
                ),
                (
                    "shop_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_item_offer",
                        to="shops.shopitem",
                    ),
                ),
            ],
        ),
    ]
