# Generated by Django 5.0.6 on 2024-06-24 11:18

import django.db.models.deletion
import utils.upload_urls
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Advert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "design",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=utils.upload_urls.advertizement_design_upload_url,
                    ),
                ),
                (
                    "website_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="advert_category",
                        to="adverts.adcategory",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="advert",
            constraint=models.UniqueConstraint(
                fields=("category", "title"), name="unique_category_title_fields"
            ),
        ),
    ]
