# Generated by Django 5.0.6 on 2024-06-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adverts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advert",
            options={"verbose_name": "Advert", "verbose_name_plural": "Adverts"},
        ),
        migrations.RemoveConstraint(
            model_name="advert",
            name="unique_category_title_fields",
        ),
    ]
