# Generated by Django 5.0.4 on 2024-05-10 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilesettings', '0009_remove_notificationsubscription_profile'),
        ('users', '0024_profile_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsubscription',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notification_profile_subscription', to='users.profile'),
            preserve_default=False,
        ),
    ]
