# Generated by Django 5.0.6 on 2024-06-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profilesettings", "0012_alter_notificationsubscription_notify_label_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="description",
            field=models.TextField(
                default="You will get only those email notification what you want.",
                help_text="News",
                max_length=255,
            ),
        ),
    ]
