# Generated by Django 5.0.6 on 2024-10-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="revenue",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
