# Generated by Django 5.0.6 on 2024-06-26 12:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_alter_article_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
