# Generated by Django 5.0.6 on 2024-06-28 06:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_template_templatecategory_article_release_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatecategory",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
