# Generated by Django 5.0.6 on 2024-06-28 09:12

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_templatecategory_timestamp"),
        ("users", "0030_profile_adverts_alter_profile_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatecategory",
            name="icon",
            field=models.CharField(default="icon ni ni-spark-fill", max_length=100),
        ),
        migrations.AlterField(
            model_name="aitoken",
            name="profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aitoken_profile",
                to="users.profile",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
    ]
