# Generated by Django 5.0.6 on 2024-06-28 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0009_aihistory"),
        ("users", "0030_profile_adverts_alter_profile_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="aihistory",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="profile_ai_history",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="aihistory",
            name="question",
            field=models.TextField(default="what is biology"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aihistory",
            name="response",
            field=models.TextField(default="humna t"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aihistory",
            name="title",
            field=models.CharField(max_length=1000),
        ),
    ]
