# Generated by Django 5.0.6 on 2024-06-28 20:13

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0010_aihistory_profile_aihistory_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aihistory",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="title"
            ),
        ),
    ]
