# Generated by Django 5.0.6 on 2024-06-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0012_article_summary_alter_article_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatecategory",
            name="color",
            field=models.CharField(
                choices=[
                    ("primary", "primary"),
                    ("secondary", "secondary"),
                    ("danger", "danger"),
                    ("info", "info"),
                    ("warning", "warning"),
                    ("success", "success"),
                ],
                default="primary",
                max_length=100,
            ),
        ),
    ]
