# Generated by Django 5.0.6 on 2024-06-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0013_templatecategory_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="article",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="article",
            name="reads",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="article",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
