# Generated by Django 5.0.6 on 2024-07-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0014_article_archived_article_featured_article_reads_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="editorsPick",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="article",
            name="sponsored",
            field=models.BooleanField(default=False),
        ),
    ]
