# Generated by Django 5.0.6 on 2024-07-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0015_article_editorspick_article_sponsored"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="recommeded",
            field=models.BooleanField(default=False),
        ),
    ]
