# Generated by Django 5.0.6 on 2024-07-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0018_ytsummarizer_duration_ytsummarizer_size_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ytsummarizer",
            name="audio_file",
        ),
        migrations.AddField(
            model_name="ytsummarizer",
            name="audio_url",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
