# Generated by Django 5.0.6 on 2024-07-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0019_remove_ytsummarizer_audio_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ytsummarizer",
            name="video_transcript",
            field=models.TextField(blank=True),
        ),
    ]
