# Generated by Django 5.0.6 on 2024-07-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0020_ytsummarizer_video_transcript"),
    ]

    operations = [
        migrations.AddField(
            model_name="ytsummarizer",
            name="transcript_file",
            field=models.URLField(blank=True),
        ),
    ]
