# Generated by Django 5.0.6 on 2024-07-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0021_ytsummarizer_transcript_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="cover",
            field=models.FileField(
                blank=True, null=True, upload_to="template/category"
            ),
        ),
        migrations.AddField(
            model_name="templatecategory",
            name="cover",
            field=models.FileField(
                blank=True, null=True, upload_to="template/category"
            ),
        ),
    ]
