# Generated by Django 5.0.6 on 2024-07-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0022_article_cover_templatecategory_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="ytsummarizer",
            name="is_verified",
            field=models.BooleanField(default=True),
        ),
    ]
