# Generated by Django 5.0.6 on 2024-07-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0023_ytsummarizer_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="ytsummarizer",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
