# Generated by Django 5.0.6 on 2024-08-29 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KenyaConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(default="KES", max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("currency_code", models.CharField(max_length=100)),
                (
                    "currency_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "amount",
                    models.FloatField(default=10, help_text="In relation to 1 KShs"),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "kenya",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="countries",
                        to="rates.kenyaconversion",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="country",
            constraint=models.UniqueConstraint(
                fields=("kenya", "country", "currency_code"),
                name="unique_kenya_country_currency_code",
            ),
        ),
    ]
