# Generated by Django 5.0.6 on 2024-06-19 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("currency_code", models.CharField(max_length=100)),
                (
                    "currency_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        default=10, help_text="In relation to 1 KShs"
                    ),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="kenyaconversion",
            name="unique_country_currency_code",
        ),
        migrations.RemoveField(
            model_name="kenyaconversion",
            name="conversion_rate",
        ),
        migrations.RemoveField(
            model_name="kenyaconversion",
            name="country",
        ),
        migrations.RemoveField(
            model_name="kenyaconversion",
            name="currency_code",
        ),
        migrations.RemoveField(
            model_name="kenyaconversion",
            name="currency_name",
        ),
        migrations.AddField(
            model_name="country",
            name="kenya",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kenya_country_conversion",
                to="rates.kenyaconversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="country",
            constraint=models.UniqueConstraint(
                fields=("kenya", "country", "currency_code"),
                name="unique_kenya_country_currency_code",
            ),
        ),
    ]
