# Generated by Django 5.0.6 on 2024-06-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0002_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kenyaconversion",
            name="amount",
        ),
        migrations.AddField(
            model_name="kenyaconversion",
            name="currency",
            field=models.CharField(default="KES", max_length=3),
        ),
    ]
