# Generated by Django 5.0.6 on 2024-06-19 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0003_remove_kenyaconversion_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="kenya",
        ),
        migrations.AddField(
            model_name="country",
            name="kenya_conversion",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="countries",
                to="rates.kenyaconversion",
            ),
            preserve_default=False,
        ),
    ]
