# Generated by Django 5.0.6 on 2024-06-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0004_remove_country_kenya_country_kenya_conversion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="country",
            old_name="kenya_conversion",
            new_name="kenya",
        ),
    ]
