# Generated by Django 5.0.6 on 2024-06-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0005_rename_kenya_conversion_country_kenya"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="amount",
            field=models.FloatField(default=10, help_text="In relation to 1 KShs"),
        ),
    ]
