# Generated by Django 5.0.4 on 2024-05-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="test", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
