# Generated by Django 5.0.6 on 2024-10-04 22:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("484233a0-cb4e-4acc-b8fc-bb2ea6a58e7c"),
                editable=False,
            ),
        ),
    ]
