# Generated by Django 5.0.6 on 2024-10-05 10:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0003_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("28e663a4-0ebf-47db-869c-7e0ed69317ce"),
                editable=False,
            ),
        ),
    ]
