# Generated by Django 5.0.4 on 2024-05-10 12:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('9c371d24-6161-4ee9-9085-d9da62117cc4'), editable=False),
        ),
    ]
