# Generated by Django 5.0.6 on 2024-10-05 12:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0005_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("0b082521-ba79-40ac-99d7-90e2b8bea1b1"),
                editable=False,
            ),
        ),
    ]
