# Generated by Django 5.0.6 on 2024-10-06 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0006_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("bdc2f62f-2030-48ec-9fa9-56460c72c4fb"),
                editable=False,
            ),
        ),
    ]
