# Generated by Django 5.0.4 on 2024-05-10 14:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0007_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("e369ec76-e5b4-4cf1-a6f2-b6eccf63d747"),
                editable=False,
            ),
        ),
    ]
