# Generated by Django 5.0.6 on 2024-10-06 19:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0007_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("56831581-b78c-4a8a-9c8c-e15fb1efda0b"),
                editable=False,
            ),
        ),
    ]
