# Generated by Django 5.0.4 on 2024-05-10 15:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0009_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("cf35387c-0ecb-4d16-b0b9-40d73db21854"),
                editable=False,
            ),
        ),
    ]
