# Generated by Django 5.0.6 on 2024-10-08 04:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0009_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("df6ccaa3-6d59-4f3a-be58-55e1faa70d1b"),
                editable=False,
            ),
        ),
    ]
