# Generated by Django 5.0.6 on 2024-10-08 04:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0010_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("25418559-31de-46a8-b12c-f3cc16feda46"),
                editable=False,
            ),
        ),
    ]
