# Generated by Django 5.0.4 on 2024-05-10 15:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0010_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('03608ab9-7af6-4bdc-ab7e-3c141404e2ce'), editable=False),
        ),
    ]
