# Generated by Django 5.0.6 on 2024-10-08 20:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0012_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("3a006dff-c15c-4a6c-8fb2-3868d12ac2e0"),
                editable=False,
            ),
        ),
    ]
