# Generated by Django 5.0.4 on 2024-05-10 17:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0013_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("85bb033f-da3e-4f61-acdf-34d769bc0e81"),
                editable=False,
            ),
        ),
    ]
