# Generated by Django 5.0.6 on 2024-10-09 12:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0014_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("3fe86de8-1e98-4417-b8cc-4fb1232015c3"),
                editable=False,
            ),
        ),
    ]
