# Generated by Django 5.0.4 on 2024-05-10 21:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0014_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("5dd1ce38-de26-4bf4-9ec1-d6b93652890a"),
                editable=False,
            ),
        ),
    ]
