# Generated by Django 5.0.6 on 2024-10-09 12:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0015_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("d9c7f335-818c-4e8c-b9a6-1121ae2756ae"),
                editable=False,
            ),
        ),
    ]
