# Generated by Django 5.0.6 on 2024-10-09 12:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0016_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("cb8dc83f-bb07-466e-b90e-4da3d2114812"),
                editable=False,
            ),
        ),
    ]
