# Generated by Django 5.0.6 on 2024-10-09 12:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0017_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("1301a717-7ee6-49e8-bda2-3e4f48335d46"),
                editable=False,
            ),
        ),
    ]
