# Generated by Django 5.0.6 on 2024-10-09 12:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0019_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("8ec974c8-e9fd-4eb2-8168-66319a216db9"),
                editable=False,
            ),
        ),
    ]
