# Generated by Django 5.0.6 on 2024-05-12 21:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0019_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("830f1cb1-69dd-4885-851e-ae418496973e"),
                editable=False,
            ),
        ),
    ]
