# Generated by Django 5.0.6 on 2024-10-09 13:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0020_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("a460fe2c-88f6-4c41-8a6d-cf2af497e41c"),
                editable=False,
            ),
        ),
    ]
