# Generated by Django 5.0.4 on 2024-05-14 07:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0021_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('addc5eef-6564-4218-89b4-29b26baf17aa'), editable=False),
        ),
    ]
