<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-05-14 19:39
=======
# Generated by Django 5.0.4 on 2024-05-14 07:42
>>>>>>> ac97029b4b35e2c247cbfa4709344a46943dd60c

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0021_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
<<<<<<< HEAD
            field=models.UUIDField(default=uuid.UUID('cf8e4b3b-1434-4cc8-ba87-5f1af4fe73db'), editable=False),
=======
            field=models.UUIDField(default=uuid.UUID('addc5eef-6564-4218-89b4-29b26baf17aa'), editable=False),
>>>>>>> ac97029b4b35e2c247cbfa4709344a46943dd60c
        ),
    ]
