# Generated by Django 5.0.6 on 2024-10-09 13:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0022_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("246a49c5-0859-4eea-b7a3-9e9fc40a8ca2"),
                editable=False,
            ),
        ),
    ]
