# Generated by Django 5.0.4 on 2024-05-14 08:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0022_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("2d4ea309-e072-4a97-8582-fcb32cb66975"),
                editable=False,
            ),
        ),
    ]
