# Generated by Django 5.0.6 on 2024-10-09 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0023_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("f30dd174-51e4-4ae6-91e8-9c14db1da78a"),
                editable=False,
            ),
        ),
    ]
