# Generated by Django 5.0.6 on 2024-10-09 14:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0024_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("79a261f4-603e-4122-a9fe-3e8f60e5963d"),
                editable=False,
            ),
        ),
    ]
