# Generated by Django 5.0.4 on 2024-05-14 08:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0024_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("ee5043fc-e7a2-4e99-8f8a-b583dae7d904"),
                editable=False,
            ),
        ),
    ]
