# Generated by Django 5.0.6 on 2024-10-09 16:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0025_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("55db266c-2f1f-47b6-8ebb-c8f7a2b7a50f"),
                editable=False,
            ),
        ),
    ]
