# Generated by Django 5.0.4 on 2024-05-14 08:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0025_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("e8e06386-1d1c-4027-bb00-3f0248877a6a"),
                editable=False,
            ),
        ),
    ]
