# Generated by Django 5.0.4 on 2024-05-14 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0026_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('e5379bd8-8e41-4c4f-a082-2dd84c2a85a9'), editable=False),
        ),
    ]
