# Generated by Django 5.0.6 on 2024-10-19 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0026_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("ee5ed1f0-92dd-4554-a098-7d85e473bee8"),
                editable=False,
            ),
        ),
    ]
