# Generated by Django 5.0.6 on 2024-10-19 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0027_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("fa7decd7-b95f-4866-9dd5-ad90ef029278"),
                editable=False,
            ),
        ),
    ]
