# Generated by Django 5.0.4 on 2024-05-14 12:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0028_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("fab88976-1882-4611-9645-b5862d7758a9"),
                editable=False,
            ),
        ),
    ]
