# Generated by Django 5.0.6 on 2024-10-19 09:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0028_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("41a7c400-8f03-43d9-a245-1485e9542a24"),
                editable=False,
            ),
        ),
    ]
