# Generated by Django 5.0.6 on 2024-10-19 10:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0029_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("36c1ab93-9d12-4bf4-a20b-f2c9b06f6c55"),
                editable=False,
            ),
        ),
    ]
