# Generated by Django 5.0.4 on 2024-05-15 08:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0030_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('525b2e08-490a-4be5-b04a-33dd3b463f3d'), editable=False),
        ),
    ]
