# Generated by Django 5.0.6 on 2024-05-15 04:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0030_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('7c22acef-d854-4168-8904-a037c1bafb1e'), editable=False),
        ),
    ]
