# Generated by Django 5.0.6 on 2024-10-19 14:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0030_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("fc129445-fb37-4449-a63d-0082d00cad4e"),
                editable=False,
            ),
        ),
    ]
