# Generated by Django 5.0.6 on 2024-10-20 00:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0031_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("0243fcdc-139b-4193-ac37-063368f5d9ca"),
                editable=False,
            ),
        ),
    ]
