# Generated by Django 5.0.4 on 2024-05-15 08:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0031_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("fa07ac85-5bcc-4195-8e3a-62dfab8ae0d5"),
                editable=False,
            ),
        ),
    ]
