# Generated by Django 5.0.4 on 2024-05-15 08:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0032_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('94d8ae82-b472-45a7-a393-a94a347da245'), editable=False),
        ),
    ]
