# Generated by Django 5.0.6 on 2024-10-20 09:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0032_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("b31f9f3b-1b31-4c0c-9c08-62ce7cb1ec1f"),
                editable=False,
            ),
        ),
    ]
