# Generated by Django 5.0.6 on 2024-10-20 10:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0033_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("1369baf0-adf5-4999-b0ad-c59f0a8824f7"),
                editable=False,
            ),
        ),
    ]
