# Generated by Django 5.0.4 on 2024-05-16 11:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0033_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("9e33109c-2517-4b39-8586-00566e87f402"),
                editable=False,
            ),
        ),
    ]
