# Generated by Django 5.0.6 on 2024-10-20 10:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0034_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("fb611e27-2e93-4955-b788-508e92a3d3ef"),
                editable=False,
            ),
        ),
    ]
