# Generated by Django 5.0.6 on 2024-10-20 12:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0035_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("bfab38a7-a827-4547-b70c-5407d94673cc"),
                editable=False,
            ),
        ),
    ]
