# Generated by Django 5.0.6 on 2024-10-20 18:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0036_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("319ebe00-c79e-4172-bbe2-8e007b1a2a95"),
                editable=False,
            ),
        ),
    ]
