# Generated by Django 5.0.4 on 2024-05-16 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0036_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("4e747aa5-43b7-468e-a2ac-97b229669c18"),
                editable=False,
            ),
        ),
    ]
