# Generated by Django 5.0.6 on 2024-10-25 06:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0036_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("2d22b541-6d82-4839-b467-f616e9ec2793"),
                editable=False,
            ),
        ),
    ]
