# Generated by Django 5.0.6 on 2024-10-27 18:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0037_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("aeb75c71-49c2-48e9-8dee-ed5ed58dd662"),
                editable=False,
            ),
        ),
    ]
