# Generated by Django 5.0.4 on 2024-05-16 11:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0037_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('9ac2f7ed-92ed-411d-9740-516d7362da48'), editable=False),
        ),
    ]
