# Generated by Django 5.0.4 on 2024-05-16 15:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0038_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('b635750c-069c-4b2d-8e02-bb961e244bd6'), editable=False),
        ),
    ]
