# Generated by Django 5.0.6 on 2024-10-27 18:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0038_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("c538808f-365c-4f20-b2a3-ee53f0aa7884"),
                editable=False,
            ),
        ),
    ]
