# Generated by Django 5.0.6 on 2024-10-27 18:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0039_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("276fc4fb-fbb9-4070-ac44-949a7fdd180b"),
                editable=False,
            ),
        ),
    ]
