# Generated by Django 5.0.6 on 2024-10-27 22:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0040_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("080ae971-87f3-48a5-b81f-3fe35b6e99d7"),
                editable=False,
            ),
        ),
    ]
