# Generated by Django 5.0.6 on 2024-10-27 23:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0041_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("98aba257-b83b-4356-9427-eedeeac97b6d"),
                editable=False,
            ),
        ),
    ]
