# Generated by Django 5.0.6 on 2024-10-28 09:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0042_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("ea50356f-7dce-46a0-9c14-4ca684ca9626"),
                editable=False,
            ),
        ),
    ]
