# Generated by Django 5.0.4 on 2024-05-17 08:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0042_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('a2eebfb3-c276-4fec-8762-f85475929dbd'), editable=False),
        ),
    ]
