# Generated by Django 5.0.6 on 2024-10-30 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0044_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("b823cbc9-8484-41c1-98d8-a678b27d9425"),
                editable=False,
            ),
        ),
    ]
