# Generated by Django 5.0.6 on 2024-11-24 08:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0045_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("4065b85e-872b-4ea3-b9e8-2d7baff95b96"),
                editable=False,
            ),
        ),
    ]
