# Generated by Django 5.0.4 on 2024-05-17 15:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0045_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('d1e1edea-9912-4f4b-ba78-d3a121270f25'), editable=False),
        ),
    ]
