# Generated by Django 5.1.4 on 2024-12-06 09:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0046_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('3f8b9b77-0329-4131-b0a3-ad73ca0a8fd4'), editable=False),
        ),
    ]
