# Generated by Django 5.0.4 on 2024-05-17 15:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0047_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('d9270816-0c4f-453c-8b6b-149352793b78'), editable=False),
        ),
    ]
