# Generated by Django 5.0.4 on 2024-05-17 17:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0048_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('ab5a6b42-fae2-4feb-b98e-1e33c581ffab'), editable=False),
        ),
    ]
