# Generated by Django 5.1.4 on 2024-12-06 16:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0048_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('f149d62b-dc9f-43a4-b26c-7f999b2f902c'), editable=False),
        ),
    ]
