# Generated by Django 5.0.6 on 2024-12-06 21:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0049_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("eb4f3a4c-3670-470e-9921-69a9524c41d9"),
                editable=False,
            ),
        ),
    ]
