# Generated by Django 5.0.6 on 2024-05-20 20:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0055_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('68be0046-a68c-41f9-af80-380e7499d42b'), editable=False),
        ),
    ]
