# Generated by Django 5.0.6 on 2024-05-20 20:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0056_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('d753f792-fd63-4519-817c-5f93c8a4ee94'), editable=False),
        ),
    ]
