# Generated by Django 5.0.4 on 2024-05-21 12:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0057_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('3349f2aa-0f62-46c4-8e3a-6d3c2e93d4cb'), editable=False),
        ),
    ]
