# Generated by Django 5.0.6 on 2024-05-20 20:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0057_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('c0e0c9b7-e5a5-4fa0-ae64-9e866b1ccf7c'), editable=False),
        ),
    ]
