# Generated by Django 5.0.6 on 2024-05-21 04:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0058_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('51bffb80-ebb3-4c16-aa44-ad44549c047f'), editable=False),
        ),
    ]
