# Generated by Django 5.0.4 on 2024-05-21 13:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0059_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("6eb93c93-6ca2-4513-b97b-f88c5cdf49d8"),
                editable=False,
            ),
        ),
    ]
