# Generated by Django 5.0.6 on 2024-05-28 10:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0062_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('bf97a604-e7c1-4a4e-8dc6-031e7e8ca7db'), editable=False),
        ),
    ]
