# Generated by Django 5.0.6 on 2024-06-01 08:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0064_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('78f55781-9861-4f69-90eb-3852e091dd6f'), editable=False),
        ),
    ]
