# Generated by Django 5.0.6 on 2024-06-03 06:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0066_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("8fc5a268-a885-4980-bca3-4be628c4b9ba"),
                editable=False,
            ),
        ),
    ]
