# Generated by Django 5.0.6 on 2024-06-03 09:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0067_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("c0bd91ff-459f-4f10-874e-fbef7fe0c583"),
                editable=False,
            ),
        ),
    ]
