# Generated by Django 5.0.6 on 2024-06-04 08:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0068_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("e88ee71e-91aa-45f0-90e1-81337fb239bd"),
                editable=False,
            ),
        ),
    ]
