# Generated by Django 5.0.6 on 2024-06-04 08:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0069_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("104696a3-140d-4c0b-8d8a-4d21eefdc895"),
                editable=False,
            ),
        ),
    ]
