# Generated by Django 5.0.6 on 2024-06-04 15:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0071_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("18506496-432e-4dbe-b967-67bd22c7b32f"),
                editable=False,
            ),
        ),
    ]
