# Generated by Django 5.0.6 on 2024-06-05 05:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0073_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("c3b432f3-e288-4be3-b533-6662b8323875"),
                editable=False,
            ),
        ),
    ]
