# Generated by Django 5.0.6 on 2024-06-05 05:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0074_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("4b5334ab-d5bc-4fe3-884c-1c0777e21cc4"),
                editable=False,
            ),
        ),
    ]
