# Generated by Django 5.0.6 on 2024-06-05 05:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0075_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("c5fd1e0d-b9fe-4d41-9789-c8145f7c64f8"),
                editable=False,
            ),
        ),
    ]
