# Generated by Django 5.0.6 on 2024-06-05 05:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0076_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("514700e8-81df-4db6-ae79-9b76f9d2c4da"),
                editable=False,
            ),
        ),
    ]
