# Generated by Django 5.0.6 on 2024-06-05 05:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0077_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("ffd3834a-1157-4de0-8233-2bff120487bc"),
                editable=False,
            ),
        ),
    ]
