# Generated by Django 5.0.6 on 2024-06-05 06:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0078_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("8238995b-b8db-4095-9ce8-57d5ee4e13da"),
                editable=False,
            ),
        ),
    ]
