# Generated by Django 5.0.6 on 2024-06-19 10:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0083_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("e9017324-5e20-4f3c-acc7-475687eefeba"),
                editable=False,
            ),
        ),
    ]
