# Generated by Django 5.0.6 on 2024-06-19 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0084_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("fca033b0-a327-4f1e-b9c6-e7e07e145c8f"),
                editable=False,
            ),
        ),
    ]
