# Generated by Django 5.0.6 on 2024-06-19 10:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0085_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("b9304b1d-20d5-4435-81e1-ecdee2154803"),
                editable=False,
            ),
        ),
    ]
