# Generated by Django 5.0.6 on 2024-06-19 10:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0086_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("302ea853-1588-48bf-89bf-e1b69e1c8805"),
                editable=False,
            ),
        ),
    ]
