# Generated by Django 5.0.6 on 2024-06-19 16:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0088_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("b0d30ef1-ae5f-4fad-b73f-101f6c6458dc"),
                editable=False,
            ),
        ),
    ]
