# Generated by Django 5.0.6 on 2024-06-20 08:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0089_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("21e5fa8d-b003-4819-844d-edc49343dac8"),
                editable=False,
            ),
        ),
    ]
