# Generated by Django 5.0.6 on 2024-06-20 08:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0090_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("83c5ed12-d39b-4080-8946-da8253dbfd10"),
                editable=False,
            ),
        ),
    ]
