# Generated by Django 5.0.6 on 2024-06-22 22:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0091_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("99555c6b-3204-4b72-81b5-16e18fa63d0b"),
                editable=False,
            ),
        ),
    ]
