# Generated by Django 5.0.6 on 2024-06-24 11:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0093_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("94a4c6fb-86f4-49e2-b309-894931a25f74"),
                editable=False,
            ),
        ),
    ]
