# Generated by Django 5.0.6 on 2024-06-24 15:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0094_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("d83c99ab-004c-44db-bad0-09608d606fcf"),
                editable=False,
            ),
        ),
    ]
