# Generated by Django 5.0.6 on 2024-06-24 15:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0095_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("22b1c884-049a-4317-9595-c779a7b74259"),
                editable=False,
            ),
        ),
    ]
