# Generated by Django 5.0.6 on 2024-06-25 09:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0096_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("1ce63cd7-ad55-49a2-8301-2d06f6c8ef27"),
                editable=False,
            ),
        ),
    ]
