# Generated by Django 5.0.6 on 2024-06-25 10:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0097_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("35d417aa-da56-4a9e-980f-1a59d0c47b29"),
                editable=False,
            ),
        ),
    ]
