# Generated by Django 5.0.6 on 2024-06-26 12:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0099_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("fe32666a-ae93-4397-9ee4-7167373d3a4e"),
                editable=False,
            ),
        ),
    ]
