# Generated by Django 5.0.6 on 2024-06-26 13:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0100_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("120b9a2c-eb27-4513-8228-3990b959f78c"),
                editable=False,
            ),
        ),
    ]
