# Generated by Django 5.0.6 on 2024-06-27 11:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0101_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("9041816a-7727-4f58-a9b4-cce77d522d71"),
                editable=False,
            ),
        ),
    ]
