<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-06-28 13:25
=======
# Generated by Django 5.0.6 on 2024-06-28 06:18
>>>>>>> fe62811d588101bfd90c9bc870efcefc28b5462e

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0102_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
<<<<<<< HEAD
                default=uuid.UUID("2f9eee33-20e1-40be-8290-1fe63b08e6ad"),
=======
                default=uuid.UUID("afdb9c5d-aa0a-41ec-a3e8-63e917dee856"),
>>>>>>> fe62811d588101bfd90c9bc870efcefc28b5462e
                editable=False,
            ),
        ),
    ]
