# Generated by Django 5.0.6 on 2024-06-28 13:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0102_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("2f9eee33-20e1-40be-8290-1fe63b08e6ad"),
                editable=False,
            ),
        ),
    ]
