# Generated by Django 5.0.6 on 2024-06-28 06:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0103_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("48503f8f-4047-47c5-a7f6-22d71893d129"),
                editable=False,
            ),
        ),
    ]
