# Generated by Django 5.0.6 on 2024-06-28 09:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0104_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("a5527b78-2d41-4b03-9921-bb9b65e3fe40"),
                editable=False,
            ),
        ),
    ]
