# Generated by Django 5.0.6 on 2024-06-28 09:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0105_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("b5d10509-a486-4bda-b1bc-892409c2976b"),
                editable=False,
            ),
        ),
    ]
