# Generated by Django 5.0.6 on 2024-06-28 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0106_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("95b56096-31ad-4994-99c0-e53c80dd9c5a"),
                editable=False,
            ),
        ),
    ]
