# Generated by Django 5.0.6 on 2024-06-28 15:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0107_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("2355aed4-d8cf-4786-86b9-f732182a8b05"),
                editable=False,
            ),
        ),
    ]
