# Generated by Django 5.0.6 on 2024-06-28 20:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0108_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("0109c6de-010f-4efa-91b2-2be53ed4e757"),
                editable=False,
            ),
        ),
    ]
