# Generated by Django 5.0.6 on 2024-06-29 06:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0109_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("55cbd7ce-8b7d-4df8-bd09-7f6dd31015bb"),
                editable=False,
            ),
        ),
    ]
