# Generated by Django 5.0.6 on 2024-06-29 09:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0110_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("5e75160a-2754-45fa-b1f7-086e7d67c1af"),
                editable=False,
            ),
        ),
    ]
