# Generated by Django 5.0.6 on 2024-06-29 11:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0111_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("b000bdd7-2852-439a-9e45-d274dccc59ba"),
                editable=False,
            ),
        ),
    ]
