# Generated by Django 5.0.6 on 2024-06-29 16:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0111_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("902f267d-b896-4b6d-9809-d8c1fc6de77a"),
                editable=False,
            ),
        ),
    ]
