# Generated by Django 5.0.6 on 2024-06-29 12:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0112_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("aa690ea6-c6a5-4873-ae4b-568588e00f78"),
                editable=False,
            ),
        ),
    ]
