# Generated by Django 5.0.6 on 2024-06-29 12:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0113_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("ebb9ac6b-c43c-4ac2-bd72-54dee888b2a5"),
                editable=False,
            ),
        ),
    ]
