# Generated by Django 5.0.6 on 2024-06-29 13:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0114_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("808788da-7687-49e9-8f82-ec9b6caf3668"),
                editable=False,
            ),
        ),
    ]
