# Generated by Django 5.0.6 on 2024-06-29 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0115_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("b9ddb1e9-9469-47b5-aa52-8fc5720b6177"),
                editable=False,
            ),
        ),
    ]
