# Generated by Django 5.0.6 on 2024-06-30 14:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0117_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("2a5ddda5-f4a7-4ebb-aa35-b1928be966cc"),
                editable=False,
            ),
        ),
    ]
