# Generated by Django 5.0.6 on 2024-06-30 23:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0119_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("4b0df0d5-9526-4114-aa6e-8d0b7363ac58"),
                editable=False,
            ),
        ),
    ]
