# Generated by Django 5.0.6 on 2024-07-01 00:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0120_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("70b6fff8-978e-4763-878b-e1cc4ec03818"),
                editable=False,
            ),
        ),
    ]
