# Generated by Django 5.0.6 on 2024-07-01 09:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0121_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("f10975e6-a179-4f80-8b46-bb62364fd343"),
                editable=False,
            ),
        ),
    ]
