# Generated by Django 5.0.6 on 2024-07-01 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0122_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("7a37699d-2650-4490-87e5-f18163d4103c"),
                editable=False,
            ),
        ),
    ]
