# Generated by Django 5.0.6 on 2024-07-01 18:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0123_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("a5f50394-ce9d-4df4-b403-fd66fd2fd6e2"),
                editable=False,
            ),
        ),
    ]
