# Generated by Django 5.0.6 on 2024-07-03 14:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0123_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("f60291f3-ac30-49d0-a2fc-26976a9384e4"),
                editable=False,
            ),
        ),
    ]
