# Generated by Django 5.0.6 on 2024-07-03 15:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0124_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("1ee53bd6-8302-4e93-b6d2-115297f32d9d"),
                editable=False,
            ),
        ),
    ]
