# Generated by Django 5.0.6 on 2024-07-02 08:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0125_alter_token_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeepGramCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("project_id", models.UUIDField(blank=True, null=True)),
                ("api_key", models.CharField(max_length=3000)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "DeepGram Credential",
                "verbose_name_plural": "DeepGram Credentials",
            },
        ),
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("a826dfa9-4b1d-4c3d-9546-e6c244ce16f3"),
                editable=False,
            ),
        ),
    ]
