# Generated by Django 5.0.6 on 2024-07-02 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0127_secretcredential_delete_deepgramcredential_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="secretcredential",
            options={
                "verbose_name": "Secret Credential",
                "verbose_name_plural": "Secret Credentials",
            },
        ),
        migrations.AlterField(
            model_name="secretcredential",
            name="name",
            field=models.CharField(
                help_text="name that will be used in the environment variable",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("96e1e147-c607-4e25-8541-c5d30bea40b2"),
                editable=False,
            ),
        ),
    ]
