# Generated by Django 5.0.6 on 2024-07-02 09:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0128_alter_secretcredential_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="secretcredential",
            name="client_id",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("0afbeffc-d1fc-4ad5-9f9d-ecbca0ef4a21"),
                editable=False,
            ),
        ),
        migrations.CreateModel(
            name="Secret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("value", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secret_credentials_source",
                        to="tokens.secretcredential",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="secret",
            constraint=models.UniqueConstraint(
                fields=("source", "name"), name="unique_secret_source_name"
            ),
        ),
    ]
