# Generated by Django 5.0.6 on 2024-07-02 13:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0129_secretcredential_client_id_alter_token_token_secret_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("c20c1bb5-d2ed-4db4-b182-21e29d476283"),
                editable=False,
            ),
        ),
    ]
