# Generated by Django 5.0.6 on 2024-07-02 16:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0130_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("22916a3f-9eb5-40ca-b02a-dbb9211432ff"),
                editable=False,
            ),
        ),
    ]
