# Generated by Django 5.0.6 on 2024-07-03 05:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0131_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("ec122f3c-282b-4718-b6be-3e332e6b274d"),
                editable=False,
            ),
        ),
    ]
