# Generated by Django 5.0.6 on 2024-07-03 11:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0132_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("2a775b16-dff8-4f7a-8eca-4c8ae6f68508"),
                editable=False,
            ),
        ),
    ]
