# Generated by Django 5.0.6 on 2024-07-03 11:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0133_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("f9205f88-60b7-47b6-831c-980101e636c0"),
                editable=False,
            ),
        ),
    ]
