# Generated by Django 5.0.6 on 2024-07-08 12:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0135_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("bab3653b-a25e-48f4-8abb-6b753a027c9d"),
                editable=False,
            ),
        ),
    ]
