# Generated by Django 5.0.6 on 2024-07-08 14:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0136_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("cf0bc61f-fc90-49f9-bee0-d9c1731e73e9"),
                editable=False,
            ),
        ),
    ]
