# Generated by Django 5.0.6 on 2024-07-08 20:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0137_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("8885cc5d-7b6a-4a91-ab87-0c54166b3098"),
                editable=False,
            ),
        ),
    ]
