# Generated by Django 5.0.6 on 2024-07-09 07:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0138_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("e1edb264-e6e9-4a8f-9e4e-dd9ac950e50f"),
                editable=False,
            ),
        ),
    ]
