# Generated by Django 5.0.6 on 2024-07-09 21:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0141_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("c6e6e6ba-f679-4e0b-93d3-993ed9ad586d"),
                editable=False,
            ),
        ),
    ]
