# Generated by Django 5.0.6 on 2024-07-10 09:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0142_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("af107a54-e48d-420e-8db4-4588e8d6c63d"),
                editable=False,
            ),
        ),
    ]
