# Generated by Django 5.0.6 on 2024-07-10 09:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0143_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("0f5c6ffe-71f6-4390-8410-c6ae9015eb32"),
                editable=False,
            ),
        ),
    ]
