# Generated by Django 5.0.6 on 2024-07-10 10:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0144_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("b2e8bdf9-cad0-4010-ab21-7a9d08e30c62"),
                editable=False,
            ),
        ),
    ]
