# Generated by Django 5.0.6 on 2024-07-10 13:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0145_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("f19044f8-3b4b-442f-aefc-91f32c9bb436"),
                editable=False,
            ),
        ),
    ]
