# Generated by Django 5.0.6 on 2024-07-11 06:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0147_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("afecb1b5-baa8-4689-8c5a-14c4bfd77c14"),
                editable=False,
            ),
        ),
    ]
