# Generated by Django 5.0.6 on 2024-07-11 07:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0148_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("17e51e02-39bf-47cc-8fd3-3945d6dd0d15"),
                editable=False,
            ),
        ),
    ]
