# Generated by Django 5.0.6 on 2024-07-11 07:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0149_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("51650bd7-eed0-4f6c-b752-a9c59cada0f9"),
                editable=False,
            ),
        ),
    ]
