# Generated by Django 5.0.6 on 2024-07-11 07:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0150_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("aeeebd87-2107-4583-ab95-4f1311777e54"),
                editable=False,
            ),
        ),
    ]
