# Generated by Django 5.0.6 on 2024-07-11 07:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0151_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("bc7866fc-4a80-4df7-970a-c06081e6931a"),
                editable=False,
            ),
        ),
    ]
