# Generated by Django 5.0.6 on 2024-07-11 07:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0152_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("38359c2d-8c5e-4d7c-92dc-df275b701f13"),
                editable=False,
            ),
        ),
    ]
