# Generated by Django 5.0.6 on 2024-07-11 07:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0153_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("11b9af99-c755-43a2-a4d5-ef3dc899a00e"),
                editable=False,
            ),
        ),
    ]
