# Generated by Django 5.0.6 on 2024-07-11 07:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0154_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("5d6da386-54fd-467e-b358-9c001f1bda0c"),
                editable=False,
            ),
        ),
    ]
