# Generated by Django 5.0.6 on 2024-07-11 07:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0156_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("c9017d83-62a3-4918-abaf-ac9cd71b013a"),
                editable=False,
            ),
        ),
    ]
