# Generated by Django 5.0.6 on 2024-07-11 08:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0157_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("8139f183-2869-40a5-ad39-59acda1fa493"),
                editable=False,
            ),
        ),
    ]
