# Generated by Django 5.0.6 on 2024-07-11 08:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0158_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("ba51e181-4f2f-4cd7-95fd-0fe356e320c9"),
                editable=False,
            ),
        ),
    ]
