# Generated by Django 5.0.6 on 2024-07-11 08:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0159_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("d898eadc-e1eb-4b65-90cb-ede77fb27f7b"),
                editable=False,
            ),
        ),
    ]
