# Generated by Django 5.0.6 on 2024-07-11 08:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0162_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("76cfa9fa-f9fd-491c-bce2-6bbcecc8a3e0"),
                editable=False,
            ),
        ),
    ]
