# Generated by Django 5.0.6 on 2024-07-11 08:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0164_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("91c0a96e-8d54-4ac1-a7e3-0cbe54558ab5"),
                editable=False,
            ),
        ),
    ]
