# Generated by Django 5.0.6 on 2024-07-11 08:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0166_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("3e726e1c-00e9-4488-87a8-0e297aa9d504"),
                editable=False,
            ),
        ),
    ]
