# Generated by Django 5.0.6 on 2024-07-11 08:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0167_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("3047f9a9-38d2-4835-985e-cba8d22e653b"),
                editable=False,
            ),
        ),
    ]
