# Generated by Django 5.0.6 on 2024-07-11 09:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0168_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("569ad7bd-88ca-448d-8d28-7eabc4e2b69a"),
                editable=False,
            ),
        ),
    ]
