# Generated by Django 5.0.6 on 2024-07-11 09:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0169_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("b03100d2-34bf-45ef-9671-7e2e4225d875"),
                editable=False,
            ),
        ),
    ]
