# Generated by Django 5.0.6 on 2024-07-11 09:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0170_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("bd1548ba-5208-4392-a5f5-4c90365c98b5"),
                editable=False,
            ),
        ),
    ]
