# Generated by Django 5.0.6 on 2024-07-11 09:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0171_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("92638f94-df01-46a4-ba50-6d9c75642310"),
                editable=False,
            ),
        ),
    ]
