# Generated by Django 5.0.6 on 2024-07-11 09:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0172_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("e38e7ac6-2315-4c15-bb75-d56896dbbbda"),
                editable=False,
            ),
        ),
    ]
