# Generated by Django 5.0.6 on 2024-07-11 09:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0173_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("b0a8b3a5-c194-4f5d-a370-fabc6aaa0493"),
                editable=False,
            ),
        ),
    ]
