# Generated by Django 5.0.6 on 2024-07-11 10:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0174_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("87c8b945-7bc7-483f-a675-72317284f85e"),
                editable=False,
            ),
        ),
    ]
