# Generated by Django 5.0.6 on 2024-07-11 10:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0175_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("48b75f18-d39d-42b2-b6e9-7d97bdaf9b83"),
                editable=False,
            ),
        ),
    ]
