# Generated by Django 5.0.6 on 2024-07-11 10:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0176_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("9145dad6-158a-407b-a285-ec067f0162aa"),
                editable=False,
            ),
        ),
    ]
