# Generated by Django 5.0.6 on 2024-07-11 11:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0177_alter_token_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("c677a3bc-e1fb-4ef0-acc5-f033e7b504b0"),
                editable=False,
            ),
        ),
    ]
