# Generated by Django 5.0.6 on 2024-08-29 07:23

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel", models.CharField(max_length=255)),
                ("icon", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("DEPOSIT", "Deposit"), ("WITHDRAWAL", "Withdrawal")],
                        max_length=22,
                        verbose_name="Transaction",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "paid",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("amount"), "-", models.F("discount")
                        ),
                        output_field=models.DecimalField(
                            decimal_places=2, default=0.0, max_digits=15
                        ),
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("is_payment_success", models.BooleanField(default=False)),
                ("receipt_number", models.CharField(blank=True, max_length=255)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("payment_phone", models.CharField(blank=True, max_length=255)),
                (
                    "mpesa_transaction_code",
                    models.CharField(blank=True, max_length=1000),
                ),
                ("payment_phone_number", models.CharField(blank=True, max_length=1000)),
                ("currency", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_account",
                        to="invest.account",
                    ),
                ),
            ],
            options={
                "get_latest_by": ["created_at"],
            },
        ),
    ]
