# Generated by Django 5.0.4 on 2024-05-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="icon",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
