# Generated by Django 5.0.4 on 2024-05-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'get_latest_by': ['created_at']},
        ),
    ]
