# Generated by Django 5.0.6 on 2024-06-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0008_transaction_mpesa_transaction_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_phone_number",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
