# Generated by Django 5.0.6 on 2024-08-29 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("streams", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="archiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archiver_messages",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="receiver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="message_receiver",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="message_sender",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="inbox",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inbox_message",
                to="streams.message",
            ),
        ),
        migrations.AddField(
            model_name="archive",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archived_messages",
                to="streams.message",
            ),
        ),
        migrations.AddField(
            model_name="admininbox",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_inbox_message",
                to="streams.message",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_update",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="room_owner",
                to="users.profile",
                verbose_name="owner",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="rooms",
            field=models.ManyToManyField(to="streams.room"),
        ),
        migrations.AddField(
            model_name="roommessage",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_messages",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="roommessage",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_messages",
                to="streams.room",
            ),
        ),
    ]
