# Generated by Django 5.0.4 on 2024-05-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='icon',
            field=models.CharField(default='', max_length=255),
        ),
    ]
