# Generated by Django 5.0.4 on 2024-05-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_room_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='icon',
            field=models.CharField(default='fi-ts-customer-service', max_length=255),
        ),
    ]
