# Generated by Django 5.0.4 on 2024-05-17 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0007_message_seen_archive"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"get_latest_by": "created_at"},
        ),
        migrations.RemoveField(
            model_name="message",
            name="message",
        ),
        migrations.CreateModel(
            name="Inbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbox_message",
                        to="streams.message",
                    ),
                ),
            ],
            options={
                "get_latest_by": "created_at",
            },
        ),
    ]
