# Generated by Django 5.0.6 on 2024-05-23 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0009_remove_message_seen_inbox_seen"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminInbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("seen", models.BooleanField(default=False)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_inbox_message",
                        to="streams.message",
                    ),
                ),
            ],
            options={
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
    ]
