# Generated by Django 5.0.6 on 2024-07-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0010_admininbox"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
    ]
