# Generated by Django 5.0.6 on 2024-07-09 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0012_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 7, 9, 7, 40, 8, 55034, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
