# Generated by Django 5.0.6 on 2024-07-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0013_post_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
