# Generated by Django 5.0.6 on 2024-07-09 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0014_post_is_active"),
        ("users", "0031_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_update",
                to="users.profile",
            ),
        ),
    ]
