# Generated by Django 5.0.6 on 2024-08-29 07:23

import amiribd.jobs.models
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="title"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="online, Nairobi, Qatar, etc", max_length=255
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("Online", "Online"),
                            ("Physical", "Physical"),
                            ("Abroad", "Abroad"),
                        ],
                        default="Online",
                        help_text="Online, Physical, Abroad, etc",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(max_length=1000)),
                ("content", models.TextField()),
                (
                    "salary_offer",
                    models.DecimalField(decimal_places=2, default=10.89, max_digits=12),
                ),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                (
                    "job_file",
                    models.FileField(
                        blank=True, null=True, upload_to="jobs/instructions/"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("A", "Career"), ("B", "Manual"), ("I", "Freelance")],
                        default="B",
                        max_length=1,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "resume_required",
                    models.BooleanField(
                        default=False,
                        help_text="This is to show whether the applicant should attach resume letter a long the application",
                    ),
                ),
                (
                    "motivation_letter_required",
                    models.BooleanField(
                        default=False,
                        help_text="This is to show whether the applicant should attach motivational letter a long the application",
                    ),
                ),
                (
                    "bidding_offer_required",
                    models.BooleanField(
                        default=False,
                        help_text="This is to show whether the applicant should place his biding while applying",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivational_letter", models.TextField(blank=True, null=True)),
                ("bidding_offer", models.TextField(blank=True, null=True)),
                (
                    "email_or_phone",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=amiribd.jobs.models.upload_application_resume,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
            },
        ),
    ]
