# Generated by Django 5.0.6 on 2024-06-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="content",
            field=models.TextField(default="Hello"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.CharField(max_length=200),
        ),
    ]
