# Generated by Django 5.0.6 on 2024-10-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="is_rejected",
            field=models.BooleanField(default=False),
        ),
    ]
