# Generated by Django 5.0.6 on 2024-06-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_job_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="job",
            name="location_type",
            field=models.CharField(
                blank=True,
                help_text="Online, Physical, Abroad, etc",
                max_length=255,
                null=True,
            ),
        ),
    ]
