# Generated by Django 5.0.6 on 2024-06-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_job_is_active_job_location_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="salary_offer",
            field=models.DecimalField(decimal_places=2, default=10.89, max_digits=12),
        ),
    ]
