# Generated by Django 5.0.6 on 2024-06-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_job_salary_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("Online", "Online"),
                    ("Physical", "Physical"),
                    ("Abroad", "Abroad"),
                ],
                default="Online",
                help_text="Online, Physical, Abroad, etc",
                max_length=20,
            ),
        ),
    ]
