# Generated by Django 5.0.6 on 2024-06-05 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_alter_job_location_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobapplication",
            old_name="cover_letter",
            new_name="motivational_letter",
        ),
    ]
