# Generated by Django 5.0.6 on 2024-06-05 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_rename_cover_letter_jobapplication_motivational_letter"),
        ("users", "0026_remove_profile_plans"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_job_applications",
                to="users.profile",
            ),
        ),
    ]
