# Generated by Django 5.0.6 on 2024-06-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_alter_jobapplication_applicant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="level",
            field=models.CharField(
                choices=[("A", "Career"), ("B", "Manual"), ("I", "Freelance")],
                default="B",
                max_length=1,
            ),
        ),
    ]
