# Generated by Django 5.0.6 on 2024-06-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_alter_jobapplication_applicant"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="motivation_letter_required",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="job",
            name="resume_required",
            field=models.BooleanField(default=True),
        ),
    ]
