# Generated by Django 5.0.6 on 2024-06-30 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_alter_job_level"),
        ("jobs", "0009_job_motivation_letter_required_job_resume_required"),
    ]

    operations = []
