# Generated by Django 5.0.6 on 2024-07-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0010_merge_20240630_0409"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="bidding_offer_required",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="bidding_offer",
            field=models.TextField(blank=True, null=True),
        ),
    ]
