# Generated by Django 5.0.6 on 2024-07-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_job_bidding_offer_required_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="bidding_offer_required",
            field=models.BooleanField(
                default=False,
                help_text="This is to show whether the applicant should place his biding while applying",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="motivation_letter_required",
            field=models.BooleanField(
                default=False,
                help_text="This is to show whether the applicant should attach motivational letter a long the application",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="resume_required",
            field=models.BooleanField(
                default=False,
                help_text="This is to show whether the applicant should attach resume letter a long the application",
            ),
        ),
    ]
