# Generated by Django 5.0.6 on 2024-07-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0012_alter_job_bidding_offer_required_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(max_length=1000),
        ),
    ]
