# Generated by Django 5.0.6 on 2024-07-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0013_alter_job_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobapplication",
            options={"get_latest_by": "created_at", "ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="job",
            name="job_file",
            field=models.FileField(
                blank=True, null=True, upload_to="jobs/instructions/"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
