# Generated by Django 5.0.6 on 2024-08-29 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invest", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pool",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pool_account_profile",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="pool",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_pool",
                to="invest.pool",
            ),
        ),
        migrations.AddField(
            model_name="poolfeature",
            name="pool",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pool_feature",
                to="invest.pool",
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pool_type",
                to="invest.pooltype",
                verbose_name="pool_type",
            ),
        ),
        migrations.AddField(
            model_name="savinginvestmentplan",
            name="scheme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="invest.savingplan",
            ),
        ),
    ]
