# Generated by Django 5.0.6 on 2024-10-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pooltype",
            name="type",
            field=models.CharField(
                choices=[
                    ("INDIVIDUAL", "Individual"),
                    ("FAMILY", "Family"),
                    ("JOINT", "Joint"),
                    ("FREELANCE", "Freelance"),
                ],
                default="INDIVIDUAL",
                max_length=10,
                unique=True,
            ),
        ),
    ]
