# Generated by Django 5.0.4 on 2024-05-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0004_delete_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='plan',
            new_name='type',
        ),
    ]
