# Generated by Django 5.0.6 on 2024-10-20 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0006_alter_pooltype_type"),
        ("users", "0006_validatedemailaddress"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestMentSaving",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "principal_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "duration_of_saving_investment",
                    models.CharField(blank=True, max_length=300),
                ),
                (
                    "interest_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "expected_daily_interest_plus_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("instruction", models.TextField(blank=True, max_length=500)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.profile",
                    ),
                ),
            ],
        ),
    ]
