# Generated by Django 5.0.6 on 2024-10-20 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0007_investmentsaving"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={
                "get_latest_by": "updated_at",
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
            },
        ),
        migrations.AddField(
            model_name="investmentsaving",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
