# Generated by Django 5.0.4 on 2024-05-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0009_alter_pooltype_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='fee',
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='type',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard')], default='Basic', max_length=10),
        ),
    ]
