# Generated by Django 5.0.4 on 2024-05-07 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0010_remove_account_fee_alter_accounttype_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="pool",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_pool",
                to="invest.pool",
            ),
        ),
    ]
