# Generated by Django 5.0.6 on 2024-10-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "invest",
            "0010_alter_investmentsaving_expected_daily_interest_plus_amount_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentsaving",
            name="expected_daily_interest_plus_amount",
            field=models.CharField(default="0.00", max_length=300),
        ),
        migrations.AlterField(
            model_name="investmentsaving",
            name="interest_amount",
            field=models.CharField(default="0.00", max_length=300),
        ),
        migrations.AlterField(
            model_name="investmentsaving",
            name="principal_amount",
            field=models.CharField(default="0.00", max_length=300),
        ),
    ]
