# Generated by Django 5.0.6 on 2024-10-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0010_alter_pooltype_type"),
        (
            "invest",
            "0011_alter_investmentsaving_expected_daily_interest_plus_amount_and_more",
        ),
    ]

    operations = []
