# Generated by Django 5.0.4 on 2024-05-08 11:52

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0012_remove_plan_percentage_return_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="type.type"
            ),
        ),
    ]
