# Generated by Django 5.1.4 on 2024-12-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0012_merge_20241030_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountwithdrawalaction',
            name='paid',
            field=models.BooleanField(default=False, help_text='Make as true if successful else leave it default False'),
        ),
        migrations.AlterField(
            model_name='accountwithdrawalaction',
            name='status',
            field=models.CharField(blank=True, choices=[('Initiated', 'Initiated'), ('Resolved', 'Resolved'), ('Cancelled', 'Cancelled')], default='Initiated', help_text='Mark this as Resolved is success payment else Cancelled', max_length=100),
        ),
    ]
