# Generated by Django 5.0.4 on 2024-05-08 12:02

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0013_plan_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="type"
            ),
        ),
    ]
