# Generated by Django 5.0.4 on 2024-05-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0015_plan_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
