# Generated by Django 5.0.4 on 2024-05-09 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0016_plan_sku"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountEventWithdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        choices=[("Withdrawal", "Withdrawal"), ("Deposit", "Deposit")],
                        default="Withdrawal",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Initiated", "Initiated"),
                            ("Resolved", "Resolved"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Initiated",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_event_action",
                        to="invest.account",
                    ),
                ),
            ],
        ),
    ]
