# Generated by Django 5.0.4 on 2024-05-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0017_accounteventwithdrawal"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounteventwithdrawal",
            name="withdrawal_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accounteventwithdrawal",
            name="withdrawal_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
