# Generated by Django 5.0.4 on 2024-05-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0021_alter_plan_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounteventwithdrawal",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
