# Generated by Django 5.0.4 on 2024-05-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0023_rename_accounteventwithdrawal_accountwithdrawalaction"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="plan",
            constraint=models.UniqueConstraint(
                fields=("account", "type"), name="unique_account_plan_type"
            ),
        ),
    ]
