# Generated by Django 5.0.4 on 2024-05-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0025_remove_plan_unique_account_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantype',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
