# Generated by Django 5.0.4 on 2024-05-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0031_alter_plantype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantype',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
