# Generated by Django 5.0.6 on 2024-06-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0034_plan_payment_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="account_ssid",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
