# Generated by Django 5.0.6 on 2024-06-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0035_account_account_ssid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"verbose_name": "Account", "verbose_name_plural": "Accounts"},
        ),
        migrations.AlterModelOptions(
            name="pool",
            options={"verbose_name": "Pool", "verbose_name_plural": "Pools"},
        ),
    ]
