# Generated by Django 5.0.6 on 2024-07-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0036_alter_account_options_alter_pool_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantype",
            name="theme",
            field=models.CharField(
                choices=[
                    ("primary", "primary"),
                    ("secondary", "secondary"),
                    ("danger", "danger"),
                    ("info", "info"),
                    ("success", "success"),
                    ("orange", "orange"),
                    ("teal", "teal"),
                    ("pink", "pink"),
                    ("azure", "azure"),
                ],
                default="orange",
                max_length=100,
            ),
        ),
    ]
