# Generated by Django 5.0.6 on 2024-07-11 09:32

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0037_plantype_theme"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "interest",
                    models.FloatField(
                        default=0.01, help_text="The interest rate charged daily"
                    ),
                ),
                (
                    "term",
                    models.IntegerField(
                        default=1, help_text="Maturation term. Example value 3 days"
                    ),
                ),
                (
                    "principal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Investment amount",
                        max_digits=15,
                    ),
                ),
                (
                    "amount",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.ExpressionWrapper(
                            django.db.models.expressions.CombinedExpression(
                                models.F("principal"),
                                "+",
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("principal"),
                                        "*",
                                        django.db.models.expressions.CombinedExpression(
                                            models.Value(1), "+", models.F("interest")
                                        ),
                                    ),
                                    "*",
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("term"), "/", models.Value(7)
                                    ),
                                ),
                            ),
                            output_field=models.DecimalField(
                                decimal_places=2, default=0.0, max_digits=15
                            ),
                        ),
                        output_field=models.DecimalField(
                            decimal_places=2, default=0.0, max_digits=15
                        ),
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavingInvestmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "approved"),
                            ("declined", "declined"),
                            ("expired", "expired"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="invest.savingplan",
                    ),
                ),
            ],
        ),
    ]
