# Generated by Django 5.0.6 on 2024-07-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0038_savingplan_savinginvestmentplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="savingplan",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
