# Generated by Django 5.0.6 on 2024-07-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0039_savingplan_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savingplan",
            name="amount",
        ),
    ]
