# Generated by Django 5.0.6 on 2024-07-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0040_remove_savingplan_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingplan",
            name="interest",
            field=models.FloatField(
                default=1, help_text="The interest rate charged daily"
            ),
        ),
    ]
