# Generated by Django 5.0.6 on 2024-07-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0041_alter_savingplan_interest"),
    ]

    operations = [
        migrations.AddField(
            model_name="savingplan",
            name="description",
            field=models.CharField(
                blank=True,
                default="Choose your investment plan and start earning.",
                max_length=300,
            ),
        ),
    ]
